### ISSUE TITLE
Complilation Error

### ISSUE THREAD

**Issue by ipa-mjp** [davetcoleman/moveit_grasps#1]
Hello,

I cloned moveit_grasp package from source for indigo_devel version and also I installed rosparam_shortcuts using binary package. When try to compile it than it gives below error.  
          " multiple definition of `rosparam_shortcuts::getBoolParam ..."

Do you have any idea what was wrong?

**Comment by davetcoleman** [comment]
Closing this because kinetic devel works well and indigo is very old
